Global:
  rec_inference_model_dir: "/raid/users/hxj/paddle/PaddleClas/inference"
  batch_size: 32
  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

RecPostProcess: null

# indexing engine config
IndexProcess:
  index_method: "HNSW32" # supported: HNSW32, IVF, Flat
  image_root: "/raid/users/hxj/datasets/dataset_km"
  index_dir: "/raid/users/hxj/paddle/PaddleClas/dataset/dataset_km/index_km"
  data_file:  "/raid/users/hxj/datasets/dataset_km/label_real.txt"
  index_operation: "new" # suported: "append", "remove", "new"
  delimiter: "\t"
  dist_type: "IP"
  embedding_size: 512
